version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre build..."
      # create virtual environment
      - virtualenv venv
      - source venv/bin/activate
      # install dependencies
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      # run tests
      - pytest
      # exit virtual environment
      - deactivate
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'