version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre build..."
      - sudo ls /root
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - pytest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'