version: '3'


services:
    web:
        build: 
            context: .
            dockerfile: app/Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"